import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/layout/Navbar";


export const metadata: Metadata = {
  title: "Conference Ticket App",
  description: "Generated by Paz",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
